// Copy this to ROKConfig.js and make your local changes there.

ROKConfig = {
  'allow_kill_monster': false,
  'always_allow_buying_cards' : false,
  'clean_up_idle_players': false,
  'initial_snot': 0,
  'log_level': "error",
  'randomize_monster_order': true,
  'top_cards': [],  // Card's to have ontop of deck after shuffeling, the first three of which will be available for purchace right away.
                    // Values represent the id of the cards in the 'theCards' object ('ACID_ATTACK' haveing id 1)
}

var english_2nd = [
  "ACID_ATTACK",
  "ALIEN_METABOLISM",
  "ALPHA_MONSTER",
  "APARTMENT_BUILDING",
  "ARMOR_PLATING",
  "BACKGROUND_DWELLER",
  "BURROWING",
  "CAMOUFLAGE",
  "COMMUTER_TRAIN",
  "COMPLETE_DESTRUCTION",
  "CORNER_STORE",
  "DEDICATED_NEWS_TEAM",
  "DROP_FROM_HIGH_ALTITUDE",
  "EATER_OF_THE_DEAD",
  "ENERGIZE",
  "ENERGY_HOARDER",
  "EVACUATION_ORDERS_X1",
  "EVACUATION_ORDERS_X2",
  "EVEN_BIGGER",
  "EXTRA_HEAD_X1",
  "EXTRA_HEAD_X2",
  "FIRE_BLAST",
  "FIRE_BREATHING",
  "FREEZE_TIME",
  "FRENZY",
  "FRIEND_OF_CHILDREN",
  "GAS_REFINERY",
  "GIANT_BRAIN",
  "GOURMET",
  "HEAL",
  "HEALING_RAY",
  "HERBIVORE",
  "HERD_CULLER",
  "HIGH_ALTITUDE_BOMBING",
  "IT_HAS_A_CHILD",
  "JET_FIGHTERS",
  "JETS",
  "MADE_IN_A_LAB",
  "METAMORPH",
  "MIMIC",
  "MONSTER_BATTERIES",
  "NATIONAL_GUARD",
  "NOVA_BREATH",
  "NUCLEAR_POWER_PLANT",
  "OMNIVORE",
  "OPPORTUNIST",
  "PARASITIC_TENTACLES",
  "PLOT_TWIST",
  "POISON_QUILLS",
  "POISON_SPIT",
  "PSYCHIC_PROBE",
  "RAPID_HEALING",
  "REGENERATION",
  "ROOTING_FOR_THE_UNDERDOG",
  "SHRINK_RAY",
  "SKYSCRAPER",
  "SMOKE_CLOUD",
  "SOLAR_POWERED",
  "SPIKED_TAIL",
  "STRETCHY",
  "TANKS",
  "TELEPATH",
  "URBAVORE",
  "VAST_STORM",
  "WERE_ONLY_MAKING_IT_STRONGER",
  "WINGS",
];

ROKConfig.deck = english_2nd;

module.exports = ROKConfig;
